# Generated by Django 5.2.5 on 2025-09-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='dni',
            field=models.CharField(default=1, max_length=15, unique=True, verbose_name='DNI'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendedor',
            name='dni',
            field=models.CharField(default=0, max_length=15, unique=True, verbose_name='DNI'),
            preserve_default=False,
        ),
    ]
